export const INDUSTRIES = [
  {
    id: "tata-motors",
    name: "Tata Motors Ltd (Pimpri Plant)",
    category: "Auto manufacturing",
    ward: "Ward 42 — Pimpri-Chinchwad",
    riskScore: 87,
    contact: {
      supervisor: "R. Kulkarni (Site Safety Officer)",
      phone: "+91 98250 41207",
      email: "safety@tatamotors.com",
      controlRoom: "+91 20 6613 1111",
      address: "Pimpri-Chinchwad Industrial Area, Pune 411018",
    },
    history: [
      {
        id: "AL-0988",
        date: "2026-08-14",
        severity: "CRITICAL",
        frp: 58.2,
        outcome: "Verified incident — paint shop fire contained",
        responseMins: 14,
      },
      {
        id: "AL-0931",
        date: "2026-06-02",
        severity: "WARNING",
        frp: 12.4,
        outcome: "Resolved — exhaust overheat",
        responseMins: 26,
      },
      {
        id: "AL-0877",
        date: "2026-03-19",
        severity: "ROUTINE",
        frp: 3.8,
        outcome: "Routine flare — scheduled maintenance",
        responseMins: 5,
      },
    ],
  },
  {
    id: "serum-institute",
    name: "Serum Institute of India",
    category: "Pharmaceuticals",
    ward: "Ward 12 — Hadapsar",
    riskScore: 64,
    contact: {
      supervisor: "S. Menon (Plant Manager)",
      phone: "+91 99048 77310",
      email: "plant@seruminstitute.com",
      controlRoom: "+91 20 2699 3900",
      address: "212/2, Hadapsar, Off Pune-Saswad Road, Pune 411028",
    },
    history: [
      {
        id: "AL-0954",
        date: "2026-07-08",
        severity: "WARNING",
        frp: 9.9,
        outcome: "False positive — steam boiler plume",
        responseMins: 18,
      },
      {
        id: "AL-0842",
        date: "2026-02-11",
        severity: "ROUTINE",
        frp: 4.4,
        outcome: "Routine maintenance",
        responseMins: 7,
      },
    ],
  },
  {
    id: "century-enka",
    name: "Century Enka Ltd",
    category: "Chemicals & Textiles",
    ward: "Ward 3 — Bhosari MIDC",
    riskScore: 92,
    contact: {
      supervisor: "A. Pathan (Yard In-charge)",
      phone: "+91 97129 55044",
      email: "safety.yard@centuryenka.com",
      controlRoom: "+91 20 6612 7300",
      address: "Bhosari MIDC, Pune 411026",
    },
    history: [
      {
        id: "AL-0975",
        date: "2026-08-01",
        severity: "WARNING",
        frp: 10.7,
        outcome: "Resolved — localized solvent fire damped",
        responseMins: 22,
      },
      {
        id: "AL-0902",
        date: "2026-05-23",
        severity: "CRITICAL",
        frp: 44.6,
        outcome: "Verified incident — reactor overheat ignition",
        responseMins: 17,
      },
    ],
  },
  {
    id: "bajaj-auto",
    name: "Bajaj Auto Ltd (Akurdi)",
    category: "Auto manufacturing",
    ward: "Ward 9 — Akurdi",
    riskScore: 58,
    contact: {
      supervisor: "V. Deshpande (Shift Superintendent)",
      phone: "+91 90990 12876",
      email: "unit3.control@bajajauto.com",
      controlRoom: "+91 20 2747 2851",
      address: "Mumbai-Pune Road, Akurdi, Pune 411035",
    },
    history: [
      {
        id: "AL-0999",
        date: "2026-09-04",
        severity: "ROUTINE",
        frp: 6.1,
        outcome: "False alarm — welding works",
        responseMins: 4,
      },
    ],
  },
  {
    id: "bank-of-india",
    name: "Bank of India (Shagun Chowk)",
    category: "Commercial Building",
    ward: "Sadashiv Peth — Laxmi Road",
    riskScore: 40,
    contact: {
      supervisor: "Branch Manager",
      phone: "020-24453495",
      email: "branch@bankofindia.co.in",
      controlRoom: "020-24488582",
      address: "592, Sadashiv Peth, Laxmi Road, Pune - 411030",
    },
    history: [
      {
        id: "AL-1044",
        date: "2026-09-29",
        severity: "CRITICAL",
        frp: 35.5,
        outcome: "Resolved — AC unit fire contained",
        responseMins: 60,
      },
    ],
  },
];

export const INITIAL_ALERTS = [
  {
    id: "AL-1044",
    location: "Sadashiv Peth — Laxmi Road",
    facility: "Bank of India (Shagun Chowk)",
    industryId: "bank-of-india",
    time: "09:30 IST",
    severity: "CRITICAL",
    priority: "High",
    classification: "Commercial Fire",
    landCover: "Urban Commercial",
    assignedOfficer: "Pune Fire Brigade",
    status: "Resolved",
    frp: 35.5,
    confidence: 99,
    lat: 18.518,
    lng: 73.851,
    position: "left-[50%] top-[50%]",
    source: "Public Report",
    detectionTime: "2026-09-29T04:00:00.000Z",
  },
  {
    id: "AL-1042",
    location: "Ward 42 — Pimpri-Chinchwad",
    facility: "Tata Motors Ltd (Pimpri Plant)",
    industryId: "tata-motors",
    time: "14:12 IST",
    severity: "CRITICAL",
    priority: "High",
    classification: "Industrial",
    landCover: "Urban Industrial",
    assignedOfficer: null,
    status: "New",
    frp: 64.8,
    confidence: 94,
    lat: 18.6225,
    lng: 73.8058,
    position: "left-[49%] top-[43%]",
    source: "VIIRS · SNPP",
    detectionTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "AL-1041",
    location: "Ward 3 — Bhosari MIDC",
    facility: "Century Enka Ltd",
    industryId: "century-enka",
    time: "13:40 IST",
    severity: "WARNING",
    priority: "Medium",
    classification: "Industrial",
    landCover: "Industrial Hub",
    assignedOfficer: "R. Sharma",
    status: "Under verification",
    frp: 12.2,
    confidence: 82,
    lat: 18.6322,
    lng: 73.826,
    position: "left-[23%] top-[66%]",
    source: "NOAA-20",
    detectionTime: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "AL-1039",
    location: "Ward 12 — Hadapsar",
    facility: "Serum Institute of India",
    industryId: "serum-institute",
    time: "11:05 IST",
    severity: "ROUTINE",
    priority: "Low",
    classification: "Industrial",
    landCover: "Urban Industrial",
    assignedOfficer: null,
    status: "Resolved",
    frp: 4.1,
    confidence: 76,
    lat: 18.502,
    lng: 73.94,
    position: "left-[72%] top-[28%]",
    source: "SEVIRI",
    detectionTime: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
];

export const INCOMING_ALERTS = [
  {
    id: "AL-1043",
    location: "Ward 9 — Akurdi",
    facility: "Bajaj Auto Ltd (Akurdi)",
    industryId: "bajaj-auto",
    time: "14:26 IST",
    severity: "CRITICAL",
    priority: "High",
    classification: "Industrial",
    landCover: "Industrial",
    assignedOfficer: null,
    status: "New",
    frp: 77.4,
    confidence: 91,
    lat: 18.6475,
    lng: 73.7915,
    position: "left-[62%] top-[62%]",
    source: "VIIRS · NOAA-21",
    detectionTime: new Date().toISOString(),
  },
];

export const MONTHLY_ALERTS = [
  { month: "Apr", critical: 4, warning: 7, routine: 14 },
  { month: "May", critical: 6, warning: 5, routine: 16 },
  { month: "Jun", critical: 3, warning: 10, routine: 11 },
  { month: "Jul", critical: 5, warning: 8, routine: 17 },
  { month: "Aug", critical: 7, warning: 9, routine: 13 },
  { month: "Sep", critical: 4, warning: 6, routine: 12 },
];

export const RESPONSE_TREND = [
  { month: "Apr", minutes: 22 },
  { month: "May", minutes: 20 },
  { month: "Jun", minutes: 18 },
  { month: "Jul", minutes: 16 },
  { month: "Aug", minutes: 14 },
  { month: "Sep", minutes: 11 },
];

export function industryById(id) {
  return INDUSTRIES.find((industry) => industry.id === id);
}
